mod 'pizzaops/cutover', '1.0.5'
mod 'puppetlabs/puppet_agent', '1.6.2'
mod 'puppetlabs/stdlib', '4.25.1'
mod 'puppetlabs/transition', '0.1.1'
mod 'puppetlabs/inifile', '2.3.0'
mod 'WhatsARanjit/node_manager', '0.7.1'
mod 'puppetlabs/apt', '5.0.1'